version: 2

jobs:
  build:
    docker:
      - image: quay.io/giantswarm/golang:1.12.6
    working_directory: /workdir
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: |
          CGO_ENABLED=0 go test -ldflags "-w -X main.gitCommit=${CIRCLE_SHA1} -linkmode 'auto' -extldflags '-static'" ./...
      - run: |
          CGO_ENABLED=0 go build -ldflags "-w -X main.gitCommit=${CIRCLE_SHA1} -linkmode 'auto' -extldflags '-static'" -o oncall-scheduler .
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run: |
          ./oncall-scheduler
      - persist_to_workspace:
          root: .
          paths:
            - ./oncall-scheduler